### ISSUE TITLE
which dataset do you use

### ISSUE THREAD

**Issue by h1deOnBush** [zwcolin/EEG-Transformer#1]
Hi
I just wonder Which dataset from BCI Competition IV are you using?

**Comment by zwcolin** [comment]
Dataset 1. A code snippet for getting the dataset has been provided in `util.py`.

**Comment by h1deOnBush** [comment]
> 

thx! And by the way, is timm a private tool repository ？

**Comment by zwcolin** [comment]
timm is a python package primarily for cv that includes implementations of different architectures, optimizers, losses, etc. Just do pip install timm and it should be good. Let me know if you have any issues caused by version incompatibility.
